import { chooseRulerStepSec, drawTimeRuler, formatTimelineTimeLabel } from "../../ui/timeline/draw/ruler.js";
import { seekTimeline, startTimelinePlayback, stopTimelinePlayback } from "./transport.js";
import {
  fitTimelineToViewport,
  getTimelineMinPxPerSec,
  clampTimelineViewportOffsetSec,
  refreshTimelineViewportAfterDurationChange,
} from "../../ui/timeline/viewport.js";
import {
  hasTimelineTrackAudioPlayback,
  getTimelinePlaybackClockAudio,
  resetTimelineTransportClockState,
  beginTimelineTransportClock,
  resolveTimelineTransportPlayheadFromClock,
  rebaseTimelineTransportClockAtCurrentPlayhead,
} from "../../infrastructure/audio/clock.js";
import { drawTimelineFrame } from "../../ui/timeline/draw/frame.js";
import { createTimelineTransportBridge } from "./transport_bridge.js";
import { createTimelineRuntimeAdapters } from "./adapters.js";

export function createTimelineTransportSubsystem({
  CONSTANTS,
  Utils,
  Drop,
  SCRUB_RUNTIME,
  MIDI_RUNTIME,
  TRACK_AUDIO_RUNTIME,
  SECTION_WAVE_RUNTIME,
  CLIP_VISUALS_RUNTIME,
  CLIP_OPS_RUNTIME,
  getTimelineMaxTimeSec,
  resumeTrackPlaybackAudioContext,
  logTransportStressEvent,
  hasUnmutedMidiTracks,
  syncTrackAudioMuteVolumes,
  syncTrackAudioPlayersToPlayhead,
  maybeRebasePlayheadFromTrackClock,
  normalizeSectionHeight,
  resolveVisibleSectionHeight,
  buildTrackRowsLayout,
  getSectionResizeHandleRectFromModule,
  isPointInSectionResizeHandleFromModule,
  buildStageGroups,
  resolveTrackStageGroup,
  isTrackMuted,
  resolveTrackPartition,
  isTrackLocked,
  getPreviewClipEdit,
  resolveEffectiveChannelMode,
  buildExplicitResourceClips,
  buildTrackClips,
  getClipId,
  applyPreviewClipGeometry,
  collectPreviewInjectedClipsForTrack,
  makeClipSelectionKey,
  resolvePrimaryClipSelectionKey,
  resolveEffectiveSelectedClipCount,
  areVideoAudioTracksLinked,
  resolveTrackStepIndex,
  renderFooter,
  collectSelectedClipRefs,
  serializePreviewClipEdits,
  emitTimelineViewState,
}) {
  const TRANSPORT_BRIDGE = createTimelineTransportBridge({
    CONSTANTS,
    Utils,
    SCRUB_RUNTIME,
    hasTimelineTrackAudioPlayback,
    getTimelinePlaybackClockAudio,
    resetTimelineTransportClockState,
    beginTimelineTransportClock,
    resolveTimelineTransportPlayheadFromClock,
    rebaseTimelineTransportClockAtCurrentPlayhead,
    seekTimeline,
    startTimelinePlayback,
    stopTimelinePlayback,
    fitTimelineToViewport,
    getTimelineMinPxPerSec,
    clampTimelineViewportOffsetSec,
    refreshTimelineViewportAfterDurationChange,
    getTimelineMaxTimeSec,
    resumeTrackPlaybackAudioContext,
    logTransportStressEvent,
    startMidiPlayback: MIDI_RUNTIME.startMidiPlayback,
    clearMidiPlayback: MIDI_RUNTIME.clearMidiPlayback,
    hasUnmutedMidiTracks,
    syncTrackAudioMuteVolumes,
    syncTrackAudioPlayersToPlayhead,
    maybeRebasePlayheadFromTrackClock,
    resolvePlaybackDurationSec: TRACK_AUDIO_RUNTIME.resolvePlaybackDurationSec,
  });

  const RUNTIME_ADAPTERS = createTimelineRuntimeAdapters({
    TRANSPORT_BRIDGE,
    SCRUB_RUNTIME,
    SECTION_WAVE_RUNTIME,
    CLIP_VISUALS_RUNTIME,
    CLIP_OPS_RUNTIME,
    CONSTANTS,
    Utils,
    normalizeSectionHeight,
    resolveVisibleSectionHeight,
    buildTrackRowsLayout,
    getSectionResizeHandleRectFromModule,
    isPointInSectionResizeHandleFromModule,
    drawTimeRuler,
    buildStageGroups,
    resolveTrackStageGroup,
    isTrackMuted,
    Drop,
    resolveTrackPartition,
    isTrackLocked,
    getPreviewClipEdit,
    formatTimelineTimeLabel,
    chooseRulerStepSec,
    resolveEffectiveChannelMode,
    buildExplicitResourceClips,
    buildTrackClips,
    getClipId,
    applyPreviewClipGeometry,
    collectPreviewInjectedClipsForTrack,
    makeClipSelectionKey,
    resolvePrimaryClipSelectionKey,
    resolveEffectiveSelectedClipCount,
    areVideoAudioTracksLinked,
    resolveTrackStepIndex,
    renderFooter,
    hasUnmutedMidiTracks,
    collectSelectedClipRefs,
    serializePreviewClipEdits,
    emitTimelineViewState,
    drawTimelineFrame,
  });

  return {
    TRANSPORT_BRIDGE,
    RUNTIME_ADAPTERS,
  };
}

