export function createTimelineState(config = {}) {
  const {
    runData,
    studioData,
    canvas,
    ctx,
    overviewLabel,
    playPauseBtn,
    jumpBtn,
    snapBtn,
    statusLabel,
    zoomLabel,
    shortcutsLabel,
    zoomResetBtn,
    skeletonModeBtn,
    compactMode = false,
    allowDurationExtend = false,
    dropTargetMode = "relaxed",
    previewQualityHint = "auto",
    externalClipThumbCache = null,
    onJumpToStep,
    onOpenRunDir,
    onDropResource,
    onClipEdit,
    onClipCut,
    onClipTrim,
    onClipJoin,
    onTrackContextAction,
    onUndo,
    onRedo,
    onResolveAudioUrl,
    onPlaybackUpdate,
    onViewStateChange,
    CONSTANTS,
    normalizeSectionHeight,
    normalizeSectionVizMode,
    normalizeSkeletonMode,
    normalizeSnapEnabled,
    normalizeTrackRowScale,
    normalizeVideoPreviewMode,
    normalizeVideoPreviewQualityHint,
  } = config;

  const readPersistedValue = (primaryKey) => {
    if (typeof localStorage === "undefined") return null;
    const primary = String(primaryKey || "").trim();
    if (!primary) return null;
    try {
      const direct = localStorage.getItem(primary);
      if (direct != null) return direct;
    } catch {}
    return null;
  };

  const initialStudioDurationSec = Math.max(0, Number(studioData?.durationSec || 0));
  const initialLockedTracks = new Set(
    (Array.isArray(studioData?.tracks) ? studioData.tracks : [])
      .filter((track) => Boolean(track?.locked))
      .map((track) => String(track?.name || "").trim())
      .filter(Boolean)
  );

  const state = {
    runData,
    studioData,
    canvas,
    ctx,
    overviewLabel,
    playPauseBtn,
    jumpBtn,
    snapBtn,
    statusLabel,
    zoomLabel,
    shortcutsLabel,
    shortcutsSignature: "",
    zoomResetBtn,
    skeletonModeBtn,
    onJumpToStep,
    onOpenRunDir,
    onDropResource,
    onClipEdit,
    onClipCut,
    onClipTrim,
    onClipJoin,
    onTrackContextAction,
    onUndo,
    onRedo,
    onResolveAudioUrl: typeof onResolveAudioUrl === "function" ? onResolveAudioUrl : null,
    onPlaybackUpdate,
    onViewStateChange: typeof onViewStateChange === "function" ? onViewStateChange : null,
    lastViewStateKey: "",
    updatePlayPauseButton: null,
    durationSec: Math.max(1, Number(studioData?.durationSec || 1)),
    t0Sec: 0,
    pxPerSec: 84,
    scrollY: 0,
    playheadSec: 0,
    isPlaying: false,
    rafId: 0,
    lastFrameTs: null,
    transportClockKind: "none",
    transportClockStartSec: 0,
    transportTimelineStartSec: 0,
    transportLastDriftSec: 0,
    transportStressDebugEnabled: false,
    transportStressDebugLastReadMs: 0,
    transportStressLogTsByKey: new Map(),
    hitRegions: [],
    selection: null,
    selectedClipKeys: new Set(),
    resizeObserver: null,
    autoFit: true,
    sectionHeight: normalizeSectionHeight(readPersistedValue(CONSTANTS.SECTION_HEIGHT_STORAGE_KEY)),
    compactMode,
    allowDurationExtend: Boolean(allowDurationExtend),
    dropTargetMode: String(dropTargetMode || "relaxed").trim().toLowerCase() === "strict" ? "strict" : "relaxed",
    resizingSection: false,
    resizeSectionPointerId: null,
    resizeSectionStartClientY: 0,
    resizeSectionStartHeight: CONSTANTS.DEFAULT_SECTION_HEIGHT,
    panningX: false,
    panPointerId: null,
    panStartClientX: 0,
    panStartT0Sec: 0,
    scrubbing: false,
    scrubPointerId: null,
    scrubResumeOnRelease: false,
    scrubLastTimeSec: 0,
    scrubLastMoveTsMs: null,
    scrubNextGrainAt: 0,
    scrubNodes: new Set(),
    scrubAudioContext: null,
    scrubAudioBuffer: null,
    scrubAudioBufferReverse: null,
    scrubSourceUrl: "",
    scrubActiveSourceUrl: "",
    scrubBufferSwapPending: false,
    scrubDecodePromise: null,
    scrubDecodeUrl: "",
    pendingTrackPointer: null,
    mutedTracks: new Set(),
    lockedTracks: initialLockedTracks,
    trackChannelModeOverrides: new Map(),
    mutePaintActive: false,
    mutePaintPointerId: null,
    mutePaintTargetMuted: false,
    mutePaintVisited: new Set(),
    sectionVizMode: normalizeSectionVizMode(readPersistedValue(CONSTANTS.SECTION_VIZ_STORAGE_KEY)),
    skeletonMode: normalizeSkeletonMode(readPersistedValue(CONSTANTS.SKELETON_MODE_STORAGE_KEY)),
    snapEnabled: normalizeSnapEnabled(readPersistedValue(CONSTANTS.TIMELINE_SNAP_STORAGE_KEY)),
    trackRowScale: normalizeTrackRowScale(readPersistedValue(CONSTANTS.TRACK_ROW_SCALE_STORAGE_KEY)),
    videoPreviewMode: normalizeVideoPreviewMode(readPersistedValue(CONSTANTS.VIDEO_PREVIEW_MODE_STORAGE_KEY)),
    previewQualityHint: normalizeVideoPreviewQualityHint(previewQualityHint),
    audio: typeof Audio === "function" ? new Audio() : null,
    audioSource: "",
    audioReady: false,
    audioErrored: false,
    audioHandlers: null,
    trackAudioPlayers: new Map(),
    trackPlaybackAudioContext: null,
    trackPlaybackMasterGain: null,
    midiAudioContext: null,
    midiNoiseBuffer: null,
    midiTrackNodes: new Map(),
    midiVoices: new Set(),
    keydownHandler: null,
    trackRows: [],
    dropTarget: null,
    dropHint: null,
    previewClipEdits: new Map(),
    clipEditSession: null,
    boxSelection: null,
    joinPreview: null,
    clipThumbCache: externalClipThumbCache instanceof Map ? externalClipThumbCache : new Map(),
    ownsClipThumbCache: !(externalClipThumbCache instanceof Map),
    filmstripRenderCache: new Map(),
    filmstripRenderCacheEpoch: 0,
    trackClockRebaseBlockedUntilMs: 0,
    cutPreview: null,
    keyupHandler: null,
    keyModifiers: { ctrl: false, shift: false, alt: false },
    trackContextMenu: null,
  };

  return { state, initialStudioDurationSec };
}
