export function createTimelinePublicApi({
  TIMELINE_STATE,
  clearTimelineInstance,
  bootstrapTimelineRender,
  wireTimelineRuntime,
  ContextMenu,
  setButtonIcon,
  stopPlayback,
  resetTransportClockState,
  clearTrackAudioPlayers,
  closeTrackPlaybackAudioBus,
  engine,
}) {
  function clearStudioTimeline(body) {
    const state = TIMELINE_STATE.get(body);
    if (!state) return;
    clearTimelineInstance({
      body,
      state,
      timelineStateMap: TIMELINE_STATE,
      ContextMenu,
      stopPlayback,
      resetTransportClockState,
      stopScrubGrains: engine.SCRUB_RUNTIME.stopScrubGrains,
      clearTrackAudioPlayers,
      closeTrackPlaybackAudioBus,
    });
  }

  function renderStudioTimeline({
    runData,
    studioData,
    body,
    layoutMode = "full",
    allowDurationExtend = false,
    dropTargetMode = "relaxed",
    previewQualityHint = "auto",
    externalClipThumbCache = null,
    initialViewState = null,
    onViewStateChange = null,
    onJumpToStep,
    onOpenRunDir,
    onResolveAudioUrl,
    onDropResource,
    onClipEdit,
    onClipCut,
    onClipTrim,
    onClipJoin,
    onTrackContextAction,
    onUndo,
    onRedo,
    onPlaybackUpdate,
  }) {
    clearStudioTimeline(body);
    body.innerHTML = "";
    const {
      compactMode,
      canvasWrap,
      canvas,
      overviewLabel,
      statusLabel,
      playPauseBtn,
      stopBtn,
      undoBtn,
      redoBtn,
      clearStudioBtn,
      fitBtn,
      snapBtn,
      sectionVizSelect,
      jumpBtn,
      shortcutsLabel,
      zoomLabel,
      zoomResetBtn,
      skeletonModeBtn,
      dpr,
      ctx,
      resolveTimelineAudioUrl,
      state,
      initialStudioDurationSec,
      hasInitialViewState,
    } = bootstrapTimelineRender({
      runData,
      studioData,
      body,
      layoutMode,
      allowDurationExtend,
      dropTargetMode,
      previewQualityHint,
      externalClipThumbCache,
      initialViewState,
      onViewStateChange,
      onJumpToStep,
      onOpenRunDir,
      onDropResource,
      onClipEdit,
      onClipCut,
      onClipTrim,
      onClipJoin,
      onTrackContextAction,
      onUndo,
      onRedo,
      onResolveAudioUrl,
      onPlaybackUpdate,
      CONSTANTS: engine.CONSTANTS,
      normalizeSectionHeight: engine.normalizeSectionHeight,
      normalizeSectionVizMode: engine.SECTION_WAVE_RUNTIME.normalizeSectionVizMode,
      normalizeSkeletonMode: engine.normalizeSkeletonMode,
      normalizeSnapEnabled: engine.normalizeSnapEnabled,
      normalizeTrackRowScale: engine.normalizeTrackRowScale,
      normalizeVideoPreviewMode: engine.normalizeVideoPreviewMode,
      normalizeVideoPreviewQualityHint: engine.normalizeVideoPreviewQualityHint,
    });
    wireTimelineRuntime({
      body,
      state,
      canvas,
      canvasWrap,
      ctx,
      dpr,
      hasInitialViewState,
      buttons: {
        playPauseBtn,
        stopBtn,
        undoBtn,
        redoBtn,
        clearStudioBtn,
        fitBtn,
        zoomResetBtn,
        jumpBtn,
        sectionVizSelect,
        snapBtn,
        skeletonModeBtn,
      },
      runtime: {
        MIDI_RUNTIME: engine.MIDI_RUNTIME,
        SCRUB_RUNTIME: engine.SCRUB_RUNTIME,
        CLIP_OPS_RUNTIME: engine.CLIP_OPS_RUNTIME,
        SECTION_WAVE_RUNTIME: engine.SECTION_WAVE_RUNTIME,
      },
      deps: {
        CONSTANTS: engine.CONSTANTS,
        Utils: engine.Utils,
        Drop: engine.Drop,
        ContextMenu,
        draw: engine.draw,
        renderOverview: engine.renderOverview,
        renderFooter: engine.renderFooter,
        fitToViewport: engine.fitToViewport,
        clampTimelineOffsetSec: engine.clampTimelineOffsetSec,
        getMinPxPerSec: engine.getMinPxPerSec,
        seek: engine.seek,
        startPlayback: engine.startPlayback,
        stopPlayback: engine.stopPlayback,
        hitTest: engine.hitTest,
        isTrackMuted: engine.isTrackMuted,
        isTrackLocked: engine.isTrackLocked,
        hasUnmutedMidiTracks: engine.hasUnmutedMidiTracks,
        setTrackMuted: engine.setTrackMuted,
        syncTrackAudioMuteVolumes: engine.syncTrackAudioMuteVolumes,
        syncTrackAudioPlayersToPlayhead: engine.syncTrackAudioPlayersToPlayhead,
        resolveTrackStageGroup: engine.resolveTrackStageGroup,
        normalizeSectionHeight: engine.normalizeSectionHeight,
        resolveEffectiveChannelMode: engine.resolveEffectiveChannelMode,
        resolveSlipOffsetFromRailHit: engine.resolveSlipOffsetFromRailHit,
        writePreviewClipEdits: engine.writePreviewClipEdits,
        resolveVisibleSectionHeight: engine.resolveVisibleSectionHeight,
        canonicalizeTargetTrackForResource: engine.canonicalizeTargetTrackForResource,
        getTrackNamesByKind: engine.getTrackNamesByKind,
        createNextTrackLaneName: engine.createNextTrackLaneName,
        deriveLinkedAudioTargetTrackFromVideo: engine.deriveLinkedAudioTargetTrackFromVideo,
        snapTimeSec: engine.snapTimeSec,
        isNearTimelineOrigin: engine.isNearTimelineOrigin,
        resolveNonOverlappingTrackName: engine.resolveNonOverlappingTrackName,
        resolveMoveDeltaBoundsForClip: engine.resolveMoveDeltaBoundsForClip,
        collectTrackNeighborBounds: engine.collectTrackNeighborBounds,
        getPreviewClipEdit: engine.getPreviewClipEdit,
        clearPreviewClipEditsForSession: engine.clearPreviewClipEditsForSession,
        replaceClipSelectionTrackKey: engine.replaceClipSelectionTrackKey,
        applyCommittedClipEditToLocalStudio: engine.applyCommittedClipEditToLocalStudio,
        setupTrackAudioPlayers: engine.setupTrackAudioPlayers,
        resolveFinalPreviewClipEdit: engine.resolveFinalPreviewClipEdit,
        onResolveAudioUrl,
        resolveTimelineAudioUrl,
        initialStudioDurationSec,
        refreshTimelineViewAfterDurationChange: engine.refreshTimelineViewAfterDurationChange,
        getPlaybackClockAudio: engine.getPlaybackClockAudio,
        findResourceDurationHintSec: engine.findResourceDurationHintSec,
        getTimelineMaxTimeSec: engine.getTimelineMaxTimeSec,
        isPointInSectionResizeHandle: engine.isPointInSectionResizeHandle,
        toggleClipSelectionFromHit: engine.toggleClipSelectionFromHit,
        clearClipSelectionSet: engine.clearClipSelectionSet,
        collectSelectedClipIdsForTrack: engine.collectSelectedClipIdsForTrack,
        normalizeTrackRowScale: engine.normalizeTrackRowScale,
        resumeTrackPlaybackAudioContext: engine.resumeTrackPlaybackAudioContext,
        logTransportStressEvent: engine.logTransportStressEvent,
        timelineStateMap: TIMELINE_STATE,
        collectLinkedClipTargets: engine.collectLinkedClipTargets,
        isClipSelectedInSet: engine.isClipSelectedInSet,
        setButtonIcon,
      },
    });
  }

  return {
    clearStudioTimeline,
    renderStudioTimeline,
  };
}
